# Generated by Django 4.1.2 on 2022-10-18 20:03

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('duoque', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='post',
            name='clip',
            field=models.ImageField(upload_to=''),
        ),
    ]
